version: "2"
services:
  apache:
    extends:
      file: ./services/apache/docker-compose.apache.yml
      service: apache
    extra_hosts:
      - "example.local:127.0.0.1"
  mysql:
    extends:
      file: ./services/mysql/docker-compose.mysql.yml
      service: mysql
  node:
    extends:
      file: ./services/node/docker-compose.node.yml
      service: node
  php:
    extends:
      file: ./services/php/docker-compose.php.yml
      service: php
  mail:
    extends:
      file: ./services/mail/docker-compose.mail.yml
      service: mail
  solr:
    extends:
      file: ./services/solr/docker-compose.solr.yml
      service: solr
volumes:
  app:
    driver_opts:
      type: none
      device: ${PWD}/src
      o: bind
