# version: "2"
# services:
#   apache:
#     extra_hosts:
#       - "drupal.local:127.0.0.1"
#   mail:
#     extra_hosts:
#       - "mail.local:127.0.0.1"
#   solr:
#     extra_hosts:
#       - "solr.local:127.0.0.1"
#   tunnel:
#     extends:
#       file: ./services/tunnel/docker-compose.yml
#       service: tunnel
#     depends_on:
#       - apache
#     environment:
#       - LT_HOST=apache
#       - LT_PORT=80
#       - LT_SUBDOMAIN=de-apache
