version: "2"
services:
  apache:
    extends:
      file: ./opt/apache/docker-compose.apache.yml
      service: apache
    extra_hosts:
      - "example.local:127.0.0.1"
  mysql:
    extends:
      file: ./opt/mysql/docker-compose.mysql.yml
      service: mysql
  node:
    extends:
      file: ./opt/node/docker-compose.node.yml
      service: node
  php:
    extends:
      file: ./opt/php/docker-compose.php.yml
      service: php
volumes:
  app:
    driver_opts:
      type: none
      device: ${PWD}/srv
      o: bind
