version: "2"
services:
  php:
    image: "digitalgardensydney/de_drupal:7.1-fpm"
    volumes:
      - ./etc/php/drush/.drush:/home/app/.drush
      - ./etc/php/drush/.acquia:/home/app/.acquia
      - ./src:/home/app/src
      - ./lib/composer:/home/app/.composer
      - $HOME/.ssh:/home/app/.ssh:ro
      - $HOME/.gitconfig:/home/app/.gitconfig:ro
      - $SSH_AUTH_SOCK:/tmp/agent.sock:ro
    environment:
      - SSH_AUTH_SOCK=/tmp/agent.sock
  httpd:
    image: "digitalgardensydney/de_apache:2.4"
    depends_on:
      - php
      - db
      - mail
    volumes:
      - ./src:/home/app/src
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./lib/mysql:/var/lib/mysql
    ports:
      - "3306"
  mail:
    image: "mailhog/mailhog"
    user: root
    environment:
      MH_API_BIND_ADDR: "0.0.0.0:80"
      MH_UI_BIND_ADDR: "0.0.0.0:80"
    ports:
      - "80"
      - "1025"
  node:
    image: "digitalgardensydney/de_node:8"
    volumes:
      - ./src:/home/app/src
      - ./lib/npm:/home/app/.npm-packages
