version: "2"
services:
  solr:
    image: solr:6
    ports:
      - "8983"
    volumes:
      - ./lib/solr:/opt/solr/server/solr/drupal
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
